server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cursort?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0  # Redis数据库索引(默认为0)
    host: localhost # Redis服务器地址
    port: 6379  # Redis服务器连接端口
    password:   # Redis服务器连接密码(默认为空)
    jedis:
      pool:
        max-active: 8  # 连接池最大连接数(使用负值表示没有限制) 默认 8
        max-wait: -1   # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认 -1
        max-idle: 8    # 连接池中的最大空闲连接 默认 8
        min-idle: 0    # 连接池中的最小空闲连接 默认 0
  servlet:
    multipart:
      max-file-size: 30MB #上传文件最大为多少兆
      max-request-size: 30MB

mybatis:
  #  mapper-locations: classpath:mapping/**/*.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shao.cursort.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 配置pagehelper参数
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql
  reasonable: false #必须为false否则当页数超出最大页数时候返回最后一页数据。如果为false 则为null

oss:
  endpoint: https://oss-cn-beijing.aliyuncs.com
  access-key-id: LTAI4FsrsD1sbXg25XYsq4uQ
  access-key-secret: Q82uwXYea117XFy48O8JN1rj3sC6H6
  bucket-name: cursort
  upload-path: root/

